services:
  api:
    build:
      context: ./api
    container_name: laravel_api
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: next_client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'video' 
      POSTGRES_USER: 'video_user'
      POSTGRES_PASSWORD: 'video_password'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups

volumes:
  db_data: